fix `AssertionError: monitoring` error for cloud tests
