{"status": "BROKEN", "subsamples": [], "test_suite": "TestAll", "duration": 0.0009350776672363281, "start_time": 1502314328.924861, "error_trace": "Traceback (most recent call last):\n  File \"/usr/lib/python2.7/unittest/case.py\", line 329, in run\n    testMethod()\n  File \"/home/dmand/src/taurus/test_all.py\", line 9, in test_erroring\n    raise Exception(\"Ima broke\")\nException: Ima broke", "error_msg": "Ima broke", "test_case": "test_erroring", "extras": {"file": "/home/dmand/src/taurus/test_all.py", "full_name": "test_all.TestAll.test_erroring", "description": null}}
{"status": "FAILED", "subsamples": [], "test_suite": "TestAll", "duration": 0.0002510547637939453, "start_time": 1502314328.925969, "error_trace": "Traceback (most recent call last):\n  File \"/usr/lib/python2.7/unittest/case.py\", line 329, in run\n    testMethod()\n  File \"/home/dmand/src/taurus/test_all.py\", line 12, in test_failing\n    self.assertEquals(2 + 2 * 2, 8)\n  File \"/usr/lib/python2.7/unittest/case.py\", line 513, in assertEqual\n    assertion_func(first, second, msg=msg)\n  File \"/usr/lib/python2.7/unittest/case.py\", line 506, in _baseAssertEqual\n    raise self.failureException(msg)\nAssertionError: 6 != 8", "error_msg": "6 != 8", "test_case": "test_failing", "extras": {"file": "/home/dmand/src/taurus/test_all.py", "full_name": "test_all.TestAll.test_failing", "description": null}}
{"status": "PASSED", "subsamples": [], "test_suite": "TestAll", "duration": 8.392333984375e-05, "start_time": 1502314328.926362, "error_trace": null, "error_msg": null, "test_case": "test_passing", "extras": {"file": "/home/dmand/src/taurus/test_all.py", "full_name": "test_all.TestAll.test_passing", "description": null}}
{"status": null, "subsamples": [], "test_suite": "TestAll", "duration": 9.298324584960938e-05, "start_time": 1502314328.926569, "error_trace": null, "error_msg": null, "test_case": "test_skipped", "extras": {"file": "/home/dmand/src/taurus/test_all.py", "full_name": "test_all.TestAll.test_skipped", "description": null}}
